service:
  flush: 1
  log_level: debug

pipeline:
  inputs:
    - name: forward
      listen: 0.0.0.0
      port: 24224
      processors:
        - name: opentelemetry_envelop
  ouputs:
    - name: opentelementry
      match: '*'
      host: ${OTLP_HOSTNAME}
      port: 4318
      headers: X-Scope-OrgID ${LOKI_ORG_ID}
        
    - name: stdout
      match: '*'