receivers:
  otlp:
    protocols:
      grpc:
      http:
        endpoint: "0.0.0:4318"

processors:
  batch:

exporter:
  debug:
    verbosity: detailed
    sampling_interval: 5s
    sampling_thereafter: 200
  otlphttp/logs:
    endpoint: "http://${env:LOKI_WRITER_ENDPOINT}/otlp"
    compression: on
    headers:
      X-Scope-OrgID: ${env:LOKI_ORG_ID}

service:
  pipelines:
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/logs, debug]
